/** Compact, bounded parent-only delegation guidance from the live registry. */

/** Guidance for resolving materially useful missing context from a child. */
export const PARENT_CONTEXT_REQUEST_GUIDANCE = `If an agent lacks context, evidence, or a decision, resolve it from the parent conversation, tools, repository evidence, or peer results when possible. Ask the user only when their input is required.

Then continue the same agent with AgentContinue, providing the missing information and new evidence. Do not replace an agent merely because it requested context.`;

/** Guidance for a follow-up turn on the same retained child session. */
export const AGENT_CONTINUE_GUIDANCE = `AgentContinue resumes the same retained child session. Send the new answer or instruction plus relevant parent/peer evidence the agent has not seen. Do not resend context already present in that session unless needed.`;

/** Immutable ownership delimiters for blocks generated by this version. */
export const ORCHESTRATION_PROMPT_MARKER = "[subagents-lean orchestration v1]";
export const ORCHESTRATION_PROMPT_END_MARKER = "[/subagents-lean orchestration v1]";
const OWNED_MARKERS = [
  ORCHESTRATION_PROMPT_MARKER,
  ORCHESTRATION_PROMPT_END_MARKER,
] as const;

const RULES = `Delegate substantive work; do known-scope, low-risk work directly: targeted reads/simple checks, minor focused edits, synthesis/bounded follow-ups. Delegate broad discovery/root-cause/design, uncertain/multiple changes, review, or verification; match roles to scope/risk; never force a full pipeline.

Own planning/decomposition/sequencing, decisions/reconciliation, integration/validation, final answer. Large tasks: investigate first; split bounded non-overlapping stages; never hand one agent the whole task.

Dependent stages sequential. Batch independent read-only foreground Agent calls in one parent turn; Pi submits them under the configured root concurrency limit. Never run overlapping writers concurrently.

Fresh agents lack parent history/tool results/peer output. Self-contained handoffs: Goal; Current state/evidence/decisions; Scope; Constraints/non-goals; Acceptance criteria; Expected result.

${PARENT_CONTEXT_REQUEST_GUIDANCE}

Reuse an existing agent only for missing information, an incomplete/conflicting result, or a bounded follow-up. Use the same writer for a focused correction within its subsystem; otherwise the parent replans ownership.

Only successfully completed retained sessions can continue; running, queued, aborted, failed, or disposed agents cannot.

${AGENT_CONTINUE_GUIDANCE}

External APIs/lifecycle/concurrency/integration require installed/upstream evidence plus a representative real sequence; synthetic mocks alone are insufficient.

Avoid review loops. When independent review is justified, set criteria/blocker bar, validate without scope expansion; stop after two independent no-blocker reviews with no material change unless checks fail or new evidence appears.`;

/** All limits are UTF-8 bytes, not JavaScript UTF-16 code units. */
export const MAX_ORCHESTRATION_NAME_LENGTH = 64;
export const MAX_ORCHESTRATION_DESCRIPTION_LENGTH = 160;
export const MAX_ORCHESTRATION_AGENTS = 24;
export const MAX_ORCHESTRATION_PROMPT_LENGTH = 4096;

const PREFIX = `${ORCHESTRATION_PROMPT_MARKER}\n${RULES}\nAgents: `;
const SUFFIX = `\n${ORCHESTRATION_PROMPT_END_MARKER}`;
const bytes = (value: string) => Buffer.byteLength(value, "utf8");
/** Maximum combined agent-list bytes after framing and rules. */
export const MAX_ORCHESTRATION_CATALOG_LENGTH = MAX_ORCHESTRATION_PROMPT_LENGTH - bytes(PREFIX) - bytes(SUFFIX);

export interface OrchestrationAgent {
  name: string;
  description: string;
  hidden?: boolean;
}

/** Reserve every extension-owned delimiter so frontmatter cannot terminate a generated block. */
function reserveOrchestrationMarkers(value: string): string {
  return value
    .replaceAll(ORCHESTRATION_PROMPT_MARKER, "[subagents-lean orchestration marker]")
    .replaceAll(ORCHESTRATION_PROMPT_END_MARKER, "[/subagents-lean orchestration marker]");
}

/** UTF-8 byte truncation at code-point boundaries. */
function truncateUtf8(value: string, limit: number): string {
  if (bytes(value) <= limit) return value;
  let result = "";
  let used = 0;
  for (const point of value) {
    const size = bytes(point);
    if (used + size > limit) break;
    result += point;
    used += size;
  }
  return result;
}

function normalizeDescription(value: string): string {
  const normalized = reserveOrchestrationMarkers(value.replace(/\s+/g, " ").trim()).replaceAll("`", "'");
  if (bytes(normalized) <= MAX_ORCHESTRATION_DESCRIPTION_LENGTH) return normalized;
  return `${truncateUtf8(normalized, Math.max(0, MAX_ORCHESTRATION_DESCRIPTION_LENGTH - bytes("…"))).trimEnd()}…`;
}

/**
 * Whether a name can be advertised without changing the exact string callers
 * must pass to Agent. Other names remain callable by their exact identifier.
 */
export function isAutomaticallyCatalogRepresentableName(name: string): boolean {
  return bytes(name) <= MAX_ORCHESTRATION_NAME_LENGTH
    && !/[`\p{Cc}\p{Zl}\p{Zp}]/u.test(name)
    && !OWNED_MARKERS.some((marker) => name.includes(marker));
}

/** Names are intentionally never normalized or truncated before advertising. */
export function normalizeOrchestrationName(name: string): string | undefined {
  return isAutomaticallyCatalogRepresentableName(name) ? name : undefined;
}

/** Normalize and cap a frontmatter description before exposing it to the parent. */
export function normalizeOrchestrationDescription(description: string): string {
  return normalizeDescription(description);
}

function overflowIndicator(omitted: number): string {
  return `; … +${omitted} omitted`;
}

/** Build bounded, deterministic guidance shown only to the parent agent. */
export function buildOrchestrationPrompt(agents: Iterable<OrchestrationAgent>): string | undefined {
  const visible = [...agents]
    .filter((agent) => agent.hidden !== true)
    .sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
  const available = visible.flatMap(({ name, description }) => {
    const advertisedName = normalizeOrchestrationName(name);
    return advertisedName === undefined
      ? []
      : [`\`${advertisedName}\` — ${normalizeOrchestrationDescription(description) || "(no description)"}`];
  });
  if (available.length === 0) {
    if (visible.length === 0) return undefined;
    return `${PREFIX}… +${visible.length} omitted${SUFFIX}`;
  }

  const entries: string[] = [];
  let catalogBytes = 0;
  for (let i = 0; i < available.length && entries.length < MAX_ORCHESTRATION_AGENTS; i++) {
    const entry = available[i]!;
    const separator = entries.length === 0 ? "" : "; ";
    const omittedAfter = visible.length - i - 1;
    const reserved = omittedAfter > 0 ? bytes(overflowIndicator(omittedAfter)) : 0;
    const remaining = MAX_ORCHESTRATION_CATALOG_LENGTH - catalogBytes - bytes(separator) - reserved;
    if (remaining < bytes(entry)) break;
    entries.push(entry);
    catalogBytes += bytes(separator) + bytes(entry);
  }

  const omitted = visible.length - entries.length;
  const catalog = `${entries.join("; ")}${omitted > 0 ? overflowIndicator(omitted) : ""}`;
  const prompt = `${PREFIX}${catalog}${SUFFIX}`;
  // Never truncate a rendered entry: advertised identifiers must remain exact.
  return bytes(prompt) <= MAX_ORCHESTRATION_PROMPT_LENGTH
    ? prompt
    : `${PREFIX}… +${visible.length} omitted${SUFFIX}`;
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Remove complete owned blocks only. v1 ownership is independent of mutable
 * guidance text, while unmatched user-authored markers remain untouched.
 */
export function stripOrchestrationPromptBlocks(prompt: string): string {
  const versioned = new RegExp(`(?:\\n\\n)?${escapeRegex(ORCHESTRATION_PROMPT_MARKER)}\\n[\\s\\S]*?\\n${escapeRegex(ORCHESTRATION_PROMPT_END_MARKER)}`, "g");
  return prompt.replace(versioned, "");
}

/** Return a parent-prompt update only when injection or removal changes it. */
export function getOrchestrationPromptUpdate(
  systemPrompt: string,
  agents: Iterable<OrchestrationAgent>,
): string | undefined {
  const withoutOwnedBlocks = stripOrchestrationPromptBlocks(systemPrompt);
  const prompt = buildOrchestrationPrompt(agents);
  if (!prompt) return withoutOwnedBlocks === systemPrompt ? undefined : withoutOwnedBlocks;

  const updated = `${withoutOwnedBlocks.trimEnd()}\n\n${prompt}`;
  return updated === systemPrompt ? undefined : updated;
}
