/** Compact, bounded parent-only delegation guidance from the live registry. */

/** Guidance for resolving materially useful missing context from a child. */
export const PARENT_CONTEXT_REQUEST_GUIDANCE = `Agents may ask for additional context, clarification, evidence, or decisions that are not available in their session.

Resolve the request from your conversation context, tools, repository evidence, or peer-agent results when possible. Ask the user only when their input is genuinely needed.

Then resume the same agent with AgentContinue, providing the requested information and any newly relevant evidence. Do not replace an agent merely because it asked for information.`;

/** Guidance for a follow-up turn on the same retained child session. */
export const AGENT_CONTINUE_GUIDANCE = `AgentContinue resumes the same retained session. Provide the requested answer or new instructions plus any relevant parent or peer evidence the agent has not seen. Do not repeat context already available in that session unless needed.`;

/** Immutable ownership delimiters for blocks generated by this version. */
export const ORCHESTRATION_PROMPT_MARKER = "[subagents-lean orchestration v1]";
export const ORCHESTRATION_PROMPT_END_MARKER = "[/subagents-lean orchestration v1]";
const OWNED_MARKERS = [
  ORCHESTRATION_PROMPT_MARKER,
  ORCHESTRATION_PROMPT_END_MARKER,
] as const;

const RULES = `Delegate substantive work; direct known-scope, low-risk work: targeted reads/simple checks, minor focused edits, synthesis/bounded follow-ups. Delegate broad discovery/root-cause/design, uncertain/multiple changes, review, or verification; unclear scope/risk calls for matching roles; never force a full pipeline.

Own planning/decomposition/sequencing, decisions/result reconciliation, integration/validation, final answer. Large tasks: investigate first; split bounded non-overlapping stages; never hand an agent the whole task.

Fresh agents lack parent history/tool results/peer output. Self-contained handoffs: Goal; Current state/evidence/decisions; Scope; Constraints/non-goals; Acceptance criteria; Expected result.

${PARENT_CONTEXT_REQUEST_GUIDANCE}

No duplicate/overlap work. Re-enter only for incomplete/conflicting results/bounded follow-up. No concurrent writers. Same writer: one focused correction/subsystem; take over/replan.

Dependent stages sequential. Batch independent read-only foreground Agent calls in one turn; Pi submits under configured root concurrency limit.

Running, queued, stopped, aborted, or failed agents cannot continue.

${AGENT_CONTINUE_GUIDANCE}

External APIs/lifecycle/concurrency/integration work require installed/upstream evidence and representative real sequence; synthetic mocks are insufficient.

Avoid repeat reviews. If justified, set criteria/blocker bar, validate without expansion; stop after two independent no-blocker reviews with no material change unless checks fail/new evidence appears.`;

/** All limits are UTF-8 bytes, not JavaScript UTF-16 code units. */
export const MAX_ORCHESTRATION_NAME_LENGTH = 64;
export const MAX_ORCHESTRATION_DESCRIPTION_LENGTH = 160;
export const MAX_ORCHESTRATION_AGENTS = 24;
export const MAX_ORCHESTRATION_PROMPT_LENGTH = 4096;

const PREFIX = `${ORCHESTRATION_PROMPT_MARKER}\n${RULES}\nAgents: `;
const SUFFIX = `\n${ORCHESTRATION_PROMPT_END_MARKER}`;
const bytes = (value: string) => Buffer.byteLength(value, "utf8");
/** Maximum combined agent-list bytes after framing and rules. */
export const MAX_ORCHESTRATION_CATALOG_LENGTH = MAX_ORCHESTRATION_PROMPT_LENGTH - bytes(PREFIX) - bytes(SUFFIX);

export interface OrchestrationAgent {
  name: string;
  description: string;
  hidden?: boolean;
}

/** Reserve every extension-owned delimiter so frontmatter cannot terminate a generated block. */
function reserveOrchestrationMarkers(value: string): string {
  return value
    .replaceAll(ORCHESTRATION_PROMPT_MARKER, "[subagents-lean orchestration marker]")
    .replaceAll(ORCHESTRATION_PROMPT_END_MARKER, "[/subagents-lean orchestration marker]");
}

/** UTF-8 byte truncation at code-point boundaries. */
function truncateUtf8(value: string, limit: number): string {
  if (bytes(value) <= limit) return value;
  let result = "";
  let used = 0;
  for (const point of value) {
    const size = bytes(point);
    if (used + size > limit) break;
    result += point;
    used += size;
  }
  return result;
}

function normalizeDescription(value: string): string {
  const normalized = reserveOrchestrationMarkers(value.replace(/\s+/g, " ").trim()).replaceAll("`", "'");
  if (bytes(normalized) <= MAX_ORCHESTRATION_DESCRIPTION_LENGTH) return normalized;
  return `${truncateUtf8(normalized, Math.max(0, MAX_ORCHESTRATION_DESCRIPTION_LENGTH - bytes("…"))).trimEnd()}…`;
}

/**
 * Whether a name can be advertised without changing the exact string callers
 * must pass to Agent. Other names remain callable by their exact identifier.
 */
export function isAutomaticallyCatalogRepresentableName(name: string): boolean {
  return bytes(name) <= MAX_ORCHESTRATION_NAME_LENGTH
    && !/[`\p{Cc}\p{Zl}\p{Zp}]/u.test(name)
    && !OWNED_MARKERS.some((marker) => name.includes(marker));
}

/** Names are intentionally never normalized or truncated before advertising. */
export function normalizeOrchestrationName(name: string): string | undefined {
  return isAutomaticallyCatalogRepresentableName(name) ? name : undefined;
}

/** Normalize and cap a frontmatter description before exposing it to the parent. */
export function normalizeOrchestrationDescription(description: string): string {
  return normalizeDescription(description);
}

function overflowIndicator(omitted: number): string {
  return `; … +${omitted} omitted`;
}

/** Build bounded, deterministic guidance shown only to the parent agent. */
export function buildOrchestrationPrompt(agents: Iterable<OrchestrationAgent>): string | undefined {
  const visible = [...agents]
    .filter((agent) => agent.hidden !== true)
    .sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
  const available = visible.flatMap(({ name, description }) => {
    const advertisedName = normalizeOrchestrationName(name);
    return advertisedName === undefined
      ? []
      : [`\`${advertisedName}\` — ${normalizeOrchestrationDescription(description) || "(no description)"}`];
  });
  if (available.length === 0) {
    if (visible.length === 0) return undefined;
    return `${PREFIX}… +${visible.length} omitted${SUFFIX}`;
  }

  const entries: string[] = [];
  let catalogBytes = 0;
  for (let i = 0; i < available.length && entries.length < MAX_ORCHESTRATION_AGENTS; i++) {
    const entry = available[i]!;
    const separator = entries.length === 0 ? "" : "; ";
    const omittedAfter = visible.length - i - 1;
    const reserved = omittedAfter > 0 ? bytes(overflowIndicator(omittedAfter)) : 0;
    const remaining = MAX_ORCHESTRATION_CATALOG_LENGTH - catalogBytes - bytes(separator) - reserved;
    if (remaining < bytes(entry)) break;
    entries.push(entry);
    catalogBytes += bytes(separator) + bytes(entry);
  }

  const omitted = visible.length - entries.length;
  const catalog = `${entries.join("; ")}${omitted > 0 ? overflowIndicator(omitted) : ""}`;
  const prompt = `${PREFIX}${catalog}${SUFFIX}`;
  // Never truncate a rendered entry: advertised identifiers must remain exact.
  return bytes(prompt) <= MAX_ORCHESTRATION_PROMPT_LENGTH
    ? prompt
    : `${PREFIX}… +${visible.length} omitted${SUFFIX}`;
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Remove complete owned blocks only. v1 ownership is independent of mutable
 * guidance text, while unmatched user-authored markers remain untouched.
 */
export function stripOrchestrationPromptBlocks(prompt: string): string {
  const versioned = new RegExp(`(?:\\n\\n)?${escapeRegex(ORCHESTRATION_PROMPT_MARKER)}\\n[\\s\\S]*?\\n${escapeRegex(ORCHESTRATION_PROMPT_END_MARKER)}`, "g");
  return prompt.replace(versioned, "");
}

/** Return a parent-prompt update only when injection or removal changes it. */
export function getOrchestrationPromptUpdate(
  systemPrompt: string,
  agents: Iterable<OrchestrationAgent>,
): string | undefined {
  const withoutOwnedBlocks = stripOrchestrationPromptBlocks(systemPrompt);
  const prompt = buildOrchestrationPrompt(agents);
  if (!prompt) return withoutOwnedBlocks === systemPrompt ? undefined : withoutOwnedBlocks;

  const updated = `${withoutOwnedBlocks.trimEnd()}\n\n${prompt}`;
  return updated === systemPrompt ? undefined : updated;
}
