/** Compact, bounded parent-only delegation guidance from the live registry. */

/** Immutable ownership delimiters for blocks generated by this version. */
export const ORCHESTRATION_PROMPT_MARKER = "[subagents-lean orchestration v1]";
export const ORCHESTRATION_PROMPT_END_MARKER = "[/subagents-lean orchestration v1]";
const OWNED_MARKERS = [
  ORCHESTRATION_PROMPT_MARKER,
  ORCHESTRATION_PROMPT_END_MARKER,
] as const;

const RULES = `Delegate substantive work; handle small, obvious, low-risk tasks directly when scope is known and a few focused tool calls suffice. Direct work may include targeted reads, simple fact checks, minor single-location edits, synthesis, and bounded follow-ups.

Delegate broad discovery, root-cause investigation, cross-component design, uncertain or multiple changes, independent review, or substantial verification. If scope or risk is unclear, use the matching role. Use only roles that add value; never force a full pipeline.

Own planning, decomposition, sequencing, decisions, result reconciliation, integration, validation, and the final response. For large tasks, investigate first, then split work into bounded, non-overlapping stages instead of handing one agent the whole request.

New agents lack parent history/tool results and peer output. For substantive spawns, use concise, decision-relevant sections: Goal; State/evidence/decisions; Scope/files/symbols; Constraints/non-goals; Acceptance criteria; Expected result.

Do not duplicate delegated work. Re-enter the same area only for incomplete or conflicting results or a bounded follow-up. Never run concurrent writers or overlapping changes. Give the same writer at most one focused correction per subsystem; then take over or re-plan with a new owner.

Run dependent work in the foreground and independent read-only work in the background. run_in_background returns immediately. After a background spawn, do useful independent work; never poll or sleep. Resume dependent work only after its completion notification.

Use AgentContinue only for finished agents; it reuses their session, so send only the new delta. Running, queued, stopped, aborted, or failed agents cannot be continued.

For external APIs, lifecycle/concurrency ordering, and integrations, require installed or upstream evidence and a representative real sequence; synthetic mocks alone are insufficient for critical paths.

Do not repeat broad review by default. If repeated review is justified, set acceptance criteria and a blocker bar, and validate findings without scope expansion. After two independent no-blocker reviews and no material change, stop unless checks fail or new evidence appears.`;

/** All limits are UTF-8 bytes, not JavaScript UTF-16 code units. */
export const MAX_ORCHESTRATION_NAME_LENGTH = 64;
export const MAX_ORCHESTRATION_DESCRIPTION_LENGTH = 160;
export const MAX_ORCHESTRATION_AGENTS = 24;
export const MAX_ORCHESTRATION_PROMPT_LENGTH = 4096;

const PREFIX = `${ORCHESTRATION_PROMPT_MARKER}\n${RULES}\nAgents: `;
const SUFFIX = `\n${ORCHESTRATION_PROMPT_END_MARKER}`;
const bytes = (value: string) => Buffer.byteLength(value, "utf8");
/** Maximum combined agent-list bytes after framing and rules. */
export const MAX_ORCHESTRATION_CATALOG_LENGTH = MAX_ORCHESTRATION_PROMPT_LENGTH - bytes(PREFIX) - bytes(SUFFIX);

export interface OrchestrationAgent {
  name: string;
  description: string;
  hidden?: boolean;
}

/** Reserve every extension-owned delimiter so frontmatter cannot terminate a generated block. */
function reserveOrchestrationMarkers(value: string): string {
  return value
    .replaceAll(ORCHESTRATION_PROMPT_MARKER, "[subagents-lean orchestration marker]")
    .replaceAll(ORCHESTRATION_PROMPT_END_MARKER, "[/subagents-lean orchestration marker]");
}

/** UTF-8 byte truncation at code-point boundaries. */
function truncateUtf8(value: string, limit: number): string {
  if (bytes(value) <= limit) return value;
  let result = "";
  let used = 0;
  for (const point of value) {
    const size = bytes(point);
    if (used + size > limit) break;
    result += point;
    used += size;
  }
  return result;
}

function normalizeDescription(value: string): string {
  const normalized = reserveOrchestrationMarkers(value.replace(/\s+/g, " ").trim()).replaceAll("`", "'");
  if (bytes(normalized) <= MAX_ORCHESTRATION_DESCRIPTION_LENGTH) return normalized;
  return `${truncateUtf8(normalized, Math.max(0, MAX_ORCHESTRATION_DESCRIPTION_LENGTH - bytes("…"))).trimEnd()}…`;
}

/**
 * Whether a name can be advertised without changing the exact string callers
 * must pass to Agent. Other names remain callable by their exact identifier.
 */
export function isAutomaticallyCatalogRepresentableName(name: string): boolean {
  return bytes(name) <= MAX_ORCHESTRATION_NAME_LENGTH
    && !/[`\p{Cc}\p{Zl}\p{Zp}]/u.test(name)
    && !OWNED_MARKERS.some((marker) => name.includes(marker));
}

/** Names are intentionally never normalized or truncated before advertising. */
export function normalizeOrchestrationName(name: string): string | undefined {
  return isAutomaticallyCatalogRepresentableName(name) ? name : undefined;
}

/** Normalize and cap a frontmatter description before exposing it to the parent. */
export function normalizeOrchestrationDescription(description: string): string {
  return normalizeDescription(description);
}

function overflowIndicator(omitted: number): string {
  return `; … +${omitted} omitted`;
}

/** Build bounded, deterministic guidance shown only to the parent agent. */
export function buildOrchestrationPrompt(agents: Iterable<OrchestrationAgent>): string | undefined {
  const visible = [...agents]
    .filter((agent) => agent.hidden !== true)
    .sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
  const available = visible.flatMap(({ name, description }) => {
    const advertisedName = normalizeOrchestrationName(name);
    return advertisedName === undefined
      ? []
      : [`\`${advertisedName}\` — ${normalizeOrchestrationDescription(description) || "(no description)"}`];
  });
  if (available.length === 0) {
    if (visible.length === 0) return undefined;
    return `${PREFIX}… +${visible.length} omitted${SUFFIX}`;
  }

  const entries: string[] = [];
  let catalogBytes = 0;
  for (let i = 0; i < available.length && entries.length < MAX_ORCHESTRATION_AGENTS; i++) {
    const entry = available[i]!;
    const separator = entries.length === 0 ? "" : "; ";
    const omittedAfter = visible.length - i - 1;
    const reserved = omittedAfter > 0 ? bytes(overflowIndicator(omittedAfter)) : 0;
    const remaining = MAX_ORCHESTRATION_CATALOG_LENGTH - catalogBytes - bytes(separator) - reserved;
    if (remaining < bytes(entry)) break;
    entries.push(entry);
    catalogBytes += bytes(separator) + bytes(entry);
  }

  const omitted = visible.length - entries.length;
  const catalog = `${entries.join("; ")}${omitted > 0 ? overflowIndicator(omitted) : ""}`;
  const prompt = `${PREFIX}${catalog}${SUFFIX}`;
  // Never truncate a rendered entry: advertised identifiers must remain exact.
  return bytes(prompt) <= MAX_ORCHESTRATION_PROMPT_LENGTH
    ? prompt
    : `${PREFIX}… +${visible.length} omitted${SUFFIX}`;
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Remove complete owned blocks only. v1 ownership is independent of mutable
 * guidance text, while unmatched user-authored markers remain untouched.
 */
export function stripOrchestrationPromptBlocks(prompt: string): string {
  const versioned = new RegExp(`(?:\\n\\n)?${escapeRegex(ORCHESTRATION_PROMPT_MARKER)}\\n[\\s\\S]*?\\n${escapeRegex(ORCHESTRATION_PROMPT_END_MARKER)}`, "g");
  return prompt.replace(versioned, "");
}

/** Return a parent-prompt update only when injection or removal changes it. */
export function getOrchestrationPromptUpdate(
  systemPrompt: string,
  enabled: boolean,
  agents: Iterable<OrchestrationAgent>,
): string | undefined {
  const withoutOwnedBlocks = stripOrchestrationPromptBlocks(systemPrompt);
  if (!enabled) return withoutOwnedBlocks === systemPrompt ? undefined : withoutOwnedBlocks;

  const prompt = buildOrchestrationPrompt(agents);
  if (!prompt) return withoutOwnedBlocks === systemPrompt ? undefined : withoutOwnedBlocks;

  const updated = `${withoutOwnedBlocks.trimEnd()}\n\n${prompt}`;
  return updated === systemPrompt ? undefined : updated;
}
